# Veri Manipülasyonu 

## Numpy

### Array oluşturma

In [1]:
import numpy as np

In [2]:
a=np.array([1,3,4,7,9])

In [3]:
a

array([1, 3, 4, 7, 9])

In [4]:
type(a)

numpy.ndarray

Sıfırdan array oluşturma

In [7]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [13]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10,4,(3,5))

array([[10.71753425,  9.21844347,  9.44605485, 12.41118891, 10.76414537],
       [ 7.6270692 ,  5.81905986, 11.41046493, 12.34747715,  8.46325526],
       [11.83556595, 12.38470817, 10.37340149,  8.98351415,  6.22273819]])

In [17]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl

In [18]:
np.random.randint(0,10,(3,5))

array([[0, 3, 6, 6, 1],
       [9, 3, 4, 8, 3],
       [1, 3, 1, 9, 9]])

Özellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [26]:
a=np.random.randint(0,10,(3,5))

In [27]:
a.ndim

2

In [28]:
a.shape

(3, 5)

In [29]:
a.size

15

### Yeniden Şekillendirme (Reshaping)

In [31]:
b=np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
c=b.reshape((3,3))
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Birleştirme (Concantenation)

In [41]:
d=np.array([1,2,3,4])
e=np.array([5,6,7,8])

In [44]:
np.concatenate([d,e])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [295]:
#iki boyut

In [48]:
f=np.array([[1,2,3],
           [4,5,6]])

In [52]:
np.concatenate([f,f]) #axis=0 satır bazında birleştirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([f,f],axis=1) #axis=0 sütun bazında birleştirme

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Array Ayırma (Splitting)

In [54]:
x=np.array([1,2,3,99,99,3,2,1])

In [55]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [56]:
a,b,c=np.split(x,[3,5])

In [57]:
a

array([1, 2, 3])

In [58]:
b

array([99, 99])

In [59]:
c

array([3, 2, 1])

In [294]:
#iki boyut

In [61]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [64]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### Sıralama (Sorting)

In [65]:
a=np.array([7,5,9,6,3,4,1])

In [66]:
np.sort(a)

array([1, 3, 4, 5, 6, 7, 9])

In [67]:
a

array([7, 5, 9, 6, 3, 4, 1])

In [69]:
a.sort()

In [70]:
a

array([1, 3, 4, 5, 6, 7, 9])

In [293]:
#iki boyut

In [73]:
x=np.random.normal(10,5,(3,3)) #ortalama=10,standart sapma=5 olacak şekilde
x

array([[ 7.61484586, 15.21118089,  8.92102824],
       [ 7.12853202,  9.258817  ,  4.03745077],
       [15.27178082, 10.29801691,  8.12219135]])

In [74]:
np.sort(x,axis=1)

array([[ 7.61484586,  8.92102824, 15.21118089],
       [ 4.03745077,  7.12853202,  9.258817  ],
       [ 8.12219135, 10.29801691, 15.27178082]])

In [75]:
np.sort(x)

array([[ 7.61484586,  8.92102824, 15.21118089],
       [ 4.03745077,  7.12853202,  9.258817  ],
       [ 8.12219135, 10.29801691, 15.27178082]])

### Index ile Elemanlara Erişmek

In [76]:
a=np.random.randint(19,size=10)
a

array([15,  5, 16, 14, 16,  4, 14,  8, 12,  4])

In [77]:
a[0]

15

In [78]:
a[0]=25
a

array([25,  5, 16, 14, 16,  4, 14,  8, 12,  4])

In [79]:
a[0:3]

array([25,  5, 16])

In [80]:
a[0::2]

array([25, 16, 16, 14, 12])

In [84]:
b=np.random.randint(19,size=(5,7))
b

array([[ 2, 12, 17, 10, 15, 14, 18],
       [13, 11, 12, 16, 15,  3, 16],
       [ 2, 13,  6, 12,  2,  6, 16],
       [14,  0,  1, 17, 11,  1, 10],
       [14,  0,  3,  5, 13,  4,  0]])

In [86]:
b[1:4,2:6]

array([[12, 16, 15,  3],
       [ 6, 12,  2,  6],
       [ 1, 17, 11,  1]])

In [87]:
b[:,:2]

array([[ 2, 12],
       [13, 11],
       [ 2, 13],
       [14,  0],
       [14,  0]])

In [88]:
#seçtiğimiz alt küme üzerinde değişiklik yaptığımızda ana array'de kalıcı olmasını istemiyorsak alt küme seçimini yaptıktan 
# .copy() methodunu kullanarak alt kümeyi kopyalayıp üstünde çalışmalar yapabiliriz.

Fancy Index ile Elemanlara Erişmek

In [89]:
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [90]:
v_alt =[1,3,5,7]
v[v_alt]

array([ 3,  9, 15, 21])

In [91]:
#iki boyut

In [92]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
row=np.array([0,1])
col=np.array([1,2])

In [95]:
m[row,col]

array([1, 5])

### Koşullu Eleman İşlemleri

In [96]:
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [97]:
v > 10

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [98]:
v[v>10]

array([12, 15, 18, 21, 24, 27])

### Matematiksel İşlemler'e Giriş

In [99]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [100]:
v*2

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [101]:
v**2

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729], dtype=int32)

In [102]:
v/5

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

# Pandas

### Pandas Dataframe Oluşturma

In [103]:
import pandas as pd

In [106]:
a=pd.Series([3,5,4,2,3,9])
a

0    3
1    5
2    4
3    2
4    3
5    9
dtype: int64

In [107]:
type(a)

pandas.core.series.Series

In [108]:
a.axes

[RangeIndex(start=0, stop=6, step=1)]

In [109]:
a.dtype

dtype('int64')

In [110]:
a.size

6

In [112]:
a.values

array([3, 5, 4, 2, 3, 9], dtype=int64)

In [113]:
a.head()

0    3
1    5
2    4
3    2
4    3
dtype: int64

sözlük üzerinden seri oluşturma

In [115]:
dic = pd.Series({"reg":10,"log":11,"cart":12})
dic

reg     10
log     11
cart    12
dtype: int64

In [116]:
pd.concat([dic,dic])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [117]:
dic.index

Index(['reg', 'log', 'cart'], dtype='object')

In [118]:
dic.keys

<bound method Series.keys of reg     10
log     11
cart    12
dtype: int64>

In [119]:
list(dic.items())

[('reg', 10), ('log', 11), ('cart', 12)]

eleman sorgulama

In [121]:
"reg" in dic

True

### Gözlem ve Değişken Seçimi: loc&iloc

In [137]:
?np.random.randint

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k

In [139]:
#methodu hatırlamadığımızda bilgi almak için "?" kullanılır

In [163]:
m=np.random.randint(1,30,size=(5,3))

In [164]:
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0     6     3    11
1     9    19    15
2    12     5    19
3    22    15    23
4     6    13    29

In [165]:
df.loc[0:3]

var1  var2  var3
0     6     3    11
1     9    19    15
2    12     5    19
3    22    15    23

In [166]:
df.iloc[0:3]

var1  var2  var3
0     6     3    11
1     9    19    15
2    12     5    19

In [142]:
#loc tanımlandığı şekilde filtreleme yapar, iloc standart filtreleme yöntemidir.

In [167]:
df.iloc[:3,:2]

var1  var2
0     6     3
1     9    19
2    12     5

In [168]:
df.iloc[0:3]["var1"]

0     6
1     9
2    12
Name: var1, dtype: int32

In [169]:
df

var1  var2  var3
0     6     3    11
1     9    19    15
2    12     5    19
3    22    15    23
4     6    13    29

In [170]:
df["var1"]

0     6
1     9
2    12
3    22
4     6
Name: var1, dtype: int32

In [171]:
df[df > 10]

var1  var2  var3
0   NaN   NaN    11
1   NaN  19.0    15
2  12.0   NaN    19
3  22.0  15.0    23
4   NaN  13.0    29

In [172]:
df[df.var1 > 10]

var1  var2  var3
2    12     5    19
3    22    15    23

In [173]:
df[df.var1 > 10]["var2"]

2     5
3    15
Name: var2, dtype: int32

### Birleştirme (Join) İşlemleri

In [174]:
df1 = df + 50
df1

var1  var2  var3
0    56    53    61
1    59    69    65
2    62    55    69
3    72    65    73
4    56    63    79

In [175]:
pd.concat([df,df1])

var1  var2  var3
0     6     3    11
1     9    19    15
2    12     5    19
3    22    15    23
4     6    13    29
0    56    53    61
1    59    69    65
2    62    55    69
3    72    65    73
4    56    63    79

In [176]:
pd.concat([df,df1],ignore_index=True)

var1  var2  var3
0     6     3    11
1     9    19    15
2    12     5    19
3    22    15    23
4     6    13    29
5    56    53    61
6    59    69    65
7    62    55    69
8    72    65    73
9    56    63    79

In [177]:
df1.columns=["var1","var2","deg1"]
df1.columns

Index(['var1', 'var2', 'deg1'], dtype='object')

In [178]:
pd.concat([df,df1],ignore_index=True)

var1  var2  var3  deg1
0     6     3  11.0   NaN
1     9    19  15.0   NaN
2    12     5  19.0   NaN
3    22    15  23.0   NaN
4     6    13  29.0   NaN
5    56    53   NaN  61.0
6    59    69   NaN  65.0
7    62    55   NaN  69.0
8    72    65   NaN  73.0
9    56    63   NaN  79.0

In [180]:
pd.concat([df,df1],join="inner",ignore_index=True)

var1  var2
0     6     3
1     9    19
2    12     5
3    22    15
4     6    13
5    56    53
6    59    69
7    62    55
8    72    65
9    56    63

In [186]:
pd.concat([df,df1],join="outer",ignore_index=True)

var1  var2  var3  deg1
0     6     3  11.0   NaN
1     9    19  15.0   NaN
2    12     5  19.0   NaN
3    22    15  23.0   NaN
4     6    13  29.0   NaN
5    56    53   NaN  61.0
6    59    69   NaN  65.0
7    62    55   NaN  69.0
8    72    65   NaN  73.0
9    56    63   NaN  79.0

In [187]:
df1=pd.DataFrame({"calisanlar":["Ali","Veli","Ayse","Fatma"],"grup":["Muhasebe","Muhendis","Muhendis","IK"]})
df1

calisanlar      grup
0        Ali  Muhasebe
1       Veli  Muhendis
2       Ayse  Muhendis
3      Fatma        IK

In [188]:
df2=pd.DataFrame({"calisanlar":["Ali","Veli","Ayse","Fatma"],"ise_giris":[2010,2009,2014,2019]})
df2

calisanlar  ise_giris
0        Ali       2010
1       Veli       2009
2       Ayse       2014
3      Fatma       2019

In [191]:
df3=pd.merge(df1,df2)
df3

calisanlar      grup  ise_giris
0        Ali  Muhasebe       2010
1       Veli  Muhendis       2009
2       Ayse  Muhendis       2014
3      Fatma        IK       2019

In [194]:
#many to one

In [193]:
df4=pd.DataFrame({"grup":["Muhasebe","Muhendis","IK"],"müdür":["Caner","Mustafa","Berkcan"]})
df4

grup    müdür
0  Muhasebe    Caner
1  Muhendis  Mustafa
2        IK  Berkcan

In [195]:
pd.merge(df3,df4)

calisanlar      grup  ise_giris    müdür
0        Ali  Muhasebe       2010    Caner
1       Veli  Muhendis       2009  Mustafa
2       Ayse  Muhendis       2014  Mustafa
3      Fatma        IK       2019  Berkcan

In [196]:
#many to many

In [198]:
df5=pd.DataFrame({"grup":["Muhasebe","Muhasebe","Muhendis","Muhendis","IK","IK"],
                  "yetenekler":["matematik","excel","kodlama","linux","excel","yönetim"]})
df5

grup yetenekler
0  Muhasebe  matematik
1  Muhasebe      excel
2  Muhendis    kodlama
3  Muhendis      linux
4        IK      excel
5        IK    yönetim

In [199]:
pd.merge(df1,df5)

calisanlar      grup yetenekler
0        Ali  Muhasebe  matematik
1        Ali  Muhasebe      excel
2       Veli  Muhendis    kodlama
3       Veli  Muhendis      linux
4       Ayse  Muhendis    kodlama
5       Ayse  Muhendis      linux
6      Fatma        IK      excel
7      Fatma        IK    yönetim

### Gruplama ve Toplulaştırma (Grouping & Aggregation)

* count()
* first()
* last()
* mean()
* median()
* mean()
* max()
* std()
* var()
* sum()

In [201]:
import seaborn as sns

In [205]:
df=sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [206]:
df.shape

(1035, 6)

In [207]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [208]:
df["mass"].mean()

2.6381605847953233

In [209]:
df["mass"].count()

513

In [210]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [211]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

### Gruplama İşlemleri

In [212]:
import pandas as pd

In [220]:
df=pd.DataFrame({"gruplar":["A","B","C","A","B","C"],"veri":[10,11,55,27,45,66]})
df.head()

gruplar  veri
0       A    10
1       B    11
2       C    55
3       A    27
4       B    45

In [221]:
df.groupby("gruplar")

In [222]:
df.groupby("gruplar").mean()

veri
gruplar      
A        18.5
B        28.0
C        60.5

In [223]:
df.groupby("gruplar").sum()

veri
gruplar      
A          37
B          56
C         121

In [224]:
df=sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [225]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [227]:
df.groupby("method")["orbital_period"].describe().T


count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

### Aggregate

In [229]:
df=pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                 "degisken1":[10,11,55,27,45,66],
                 "degisken2":[120,115,515,727,145,666]})
df

gruplar  degisken1  degisken2
0       A         10        120
1       B         11        115
2       C         55        515
3       A         27        727
4       B         45        145
5       C         66        666

In [230]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             18.5      423.5
B             28.0      130.0
C             60.5      590.5

In [234]:
df.groupby("gruplar").aggregate([min,np.median,max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   18.5  27       120  423.5  727
B              11   28.0  45       115  130.0  145
C              55   60.5  66       515  590.5  666

In [235]:
df.groupby("gruplar").aggregate({"degisken1":min,"degisken2":max})

degisken1  degisken2
gruplar                      
A               10        727
B               11        145
C               55        666

### Filter

In [236]:
df

gruplar  degisken1  degisken2
0       A         10        120
1       B         11        115
2       C         55        515
3       A         27        727
4       B         45        145
5       C         66        666

In [239]:
def filter_func(x):
    return x["degisken1"].std()>10

In [240]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
0       A         10        120
1       B         11        115
3       A         27        727
4       B         45        145

### Transform

In [242]:
df1=df.iloc[:,1:3]
df1

degisken1  degisken2
0         10        120
1         11        115
2         55        515
3         27        727
4         45        145
5         66        666

In [249]:
df1.transform(lambda x:(x-x.mean())/x.std())

degisken1  degisken2
0  -1.099776  -0.908779
1  -1.056927  -0.926166
2   0.828402   0.464822
3  -0.371353   1.202045
4   0.399918  -0.821842
5   1.299735   0.989920

### Apply

In [251]:
df1

degisken1  degisken2
0         10        120
1         11        115
2         55        515
3         27        727
4         45        145
5         66        666

In [254]:
df1.sum()

degisken1     214
degisken2    2288
dtype: int64

In [255]:
df1.apply(np.sum)

degisken1     214
degisken2    2288
dtype: int64

In [259]:
df.groupby("gruplar").apply(np.mean)

degisken1  degisken2
gruplar                      
A             18.5      423.5
B             28.0      130.0
C             60.5      590.5

In [260]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             18.5      423.5
B             28.0      130.0
C             60.5      590.5

### Pivot Tablolar

In [264]:
titanic=sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [265]:
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [267]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [270]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [271]:
titanic.pivot_table("survived",index="sex",columns="class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [272]:
titanic.age.mean()

29.69911764705882

In [273]:
titanic["age"].mean()

29.69911764705882

In [275]:
titanic["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [279]:
age=pd.cut(titanic["age"],[0,25,50,75])
age

0       (0.0, 25.0]
1      (25.0, 50.0]
2      (25.0, 50.0]
3      (25.0, 50.0]
4      (25.0, 50.0]
           ...     
886    (25.0, 50.0]
887     (0.0, 25.0]
888             NaN
889    (25.0, 50.0]
890    (25.0, 50.0]
Name: age, Length: 891, dtype: category
Categories (3, interval[int64]): [(0, 25] < (25, 50] < (50, 75]]

In [281]:
titanic.pivot_table("survived",["sex",age],"class")

class               First    Second     Third
sex    age                                   
female (0, 25]   0.928571  0.965517  0.507692
       (25, 50]  0.977273  0.904762  0.361111
       (50, 75]  1.000000  0.666667  1.000000
male   (0, 25]   0.500000  0.277778  0.155039
       (25, 50]  0.459016  0.078431  0.156522
       (50, 75]  0.160000  0.083333  0.000000

### Dış Kaynaklı Veri Okuma

In [282]:
pd.read_csv("reading_data/ornekcsv.csv")

a;b;c
0    78;12;1
1    78;12;2
2   78;324;3
3      7;2;4
4    88;23;5
5       6;2;
6    56;11;6
7     7;12;7
8    56;21;7
9    346;2;8
10     5;1;8
11  456;21;8
12   3;12;88

In [283]:
pd.read_csv("reading_data/ornekcsv.csv",sep=";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [287]:
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [290]:
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0